# Generated by Django 4.1.1 on 2022-10-04 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("institute", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("science", "B.Sc"),
                            ("commerce", "B.BA"),
                            ("arts", "B.A"),
                        ],
                        default="waiscienceting",
                        max_length=255,
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="institute.institute",
                    ),
                ),
            ],
        ),
    ]
