# Generated by Django 4.1.1 on 2022-10-05 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='institute',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='department',
            name='degree',
            field=models.CharField(choices=[('science', 'B.Sc'), ('commerce', 'B.BA'), ('arts', 'B.A')], default='science', max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='institute.institute'),
        ),
    ]
